In [1]:
import numpy as np

In [2]:
data = np.arange(10)
print(data)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# 类型,所有元素必须相同
print(data.dtype)

# shape
print(data.shape)

# 维度
print(data.ndim)

# size
print(data.size)


int32
(10,)
1
10


In [4]:
# 数据类型，转化
arr1 = np.array([1,2,3],dtype=np.int32)
print(arr1)
print(arr1.dtype)

arr_float = arr1.astype(np.float64)
print(arr_float)
print(arr_float.dtype)



[1 2 3]
int32
[ 1.  2.  3.]
float64


In [5]:
# 注意切片是原始数据的视图
arr = np.arange(10)
print(arr)

arr_slice = arr[0:3]
arr_slice[:] = 100
print(arr_slice)
print(arr)

# 如果只想要副本，只能显式复制
arr_copy = arr[0:3].copy()
arr_copy[:] = 1000
print(arr_copy)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[100 100 100]
[100 100 100   3   4   5   6   7   8   9]
[1000 1000 1000]
[100 100 100   3   4   5   6   7   8   9]


In [6]:
# bool索引
name = np.array(["a","b","c","d"])
print(name)
number = np.arange(20).reshape((4,5))
print(number)


['a' 'b' 'c' 'd']
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [7]:
mask = (name=="a")|(name!="c") # == / != / -(否定) / |(或) / &(和) 
print(mask)
print(number[mask,:1])  

[ True  True False  True]
[[ 0]
 [ 5]
 [15]]


In [8]:
# 通过bool索引返回的数据是数据的副本
print(number)
new_number = number[number % 3 == 0]
print(new_number)
new_number[:]=0 # 数据的副本，修改对原数据不影响
print(new_number)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  3  6  9 12 15 18]
[0 0 0 0 0 0 0]


In [9]:
# 利用数组进行索引——花式索引

arr2 = np.zeros((5,4))
for i in range(5):
    arr2[i] = i
print(arr2)
array1 = [0,2,4]
array2 = [0,2,3]
print(arr2[array1])                  # 第0,2,4行
print(arr2[array1,array2])           # 元素(0,0)(2,2)(4,3)
print(arr2[np.ix_(array1,array2)])   # 第0,2,4行，第0,2,3列

[[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]]
[[ 0.  0.  0.  0.]
 [ 2.  2.  2.  2.]
 [ 4.  4.  4.  4.]]
[ 0.  2.  4.]
[[ 0.  0.  0.]
 [ 2.  2.  2.]
 [ 4.  4.  4.]]


In [10]:
# 网格数据

x = np.arange(0,5)
y = np.arange(5,10)
xx,yy = np.meshgrid(x,y)
print(xx)  # 数据横着不同
print(yy)  # 数据竖着不同

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[5 5 5 5 5]
 [6 6 6 6 6]
 [7 7 7 7 7]
 [8 8 8 8 8]
 [9 9 9 9 9]]


In [11]:
# where函数

wh = np.arange(15).reshape((3,5))
print(wh)
print(np.where(wh%3==0)) # (0,0)(0,3)(1,1)(1,4)(2,2)
print(np.where(wh%3==0)[0])
print(np.where(wh%3==0)[1])
wh_ = np.where(wh%3==0,100,wh) #只改变符合条件的值
print(wh)
print(wh_) # 是新的数组，副本


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(array([0, 0, 1, 1, 2], dtype=int64), array([0, 3, 1, 4, 2], dtype=int64))
[0 0 1 1 2]
[0 3 1 4 2]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[100   1   2 100   4]
 [  5 100   7   8 100]
 [ 10  11 100  13  14]]


In [12]:
# 数轴axis
print(arr2)
print(arr2.sum(axis=0)) #axis=0 竖着
print(arr2.sum(axis=1)) #axis=1 横着

[[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]]
[ 10.  10.  10.  10.]
[  0.   4.   8.  12.  16.]


In [13]:
# 随机数
# rand()均匀分布
# randn()正态分布
# 创建一个给定形状的数组，并使用来自[0, 1)的均匀分布的随机样本填充它。
print(np.random.rand(5))
print(np.random.rand(3,2))


[ 0.61954337  0.44446828  0.2720998   0.47191041  0.87689288]
[[ 0.45327552  0.70376625]
 [ 0.01614912  0.13921207]
 [ 0.16292806  0.93124735]]


In [14]:
# randint(low,high=None,size=None)
print(np.random.randint(2,size=10))
print(np.random.randint(2,5,size=(3,2)))

[1 0 1 1 1 0 0 1 1 1]
[[2 4]
 [3 4]
 [2 4]]


In [15]:
# numpy快速入门教程
# https://yiyibooks.cn/xx/NumPy_v111/user/quickstart.html